# Generated by Django 2.2 on 2019-05-28 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowmaterialprice',
            name='deprecated',
            field=models.FloatField(default=False, help_text='SoloProductItem puede haber 1 precio por producto, si activa este, los otros se desactivan.', verbose_name='Activo'),
        ),
        migrations.CreateModel(
            name='ProducedReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'plantilla',
                'verbose_name_plural': 'plantillas',
            },
        ),
        migrations.CreateModel(
            name='ProducedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Product', verbose_name='Producto')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.ProducedReport', verbose_name='plantilla')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
