# Generated by Django 2.2 on 2019-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_auto_20190528_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowmaterialprice',
            name='deprecated',
            field=models.FloatField(default=False, help_text='Solo puede haber 1 precio por producto, si activa este, los otros se desactivan.', verbose_name='Activo'),
        ),
    ]
