# Generated by Django 2.1.5 on 2019-04-08 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('name', models.CharField(max_length=128, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=65, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=128, null=True, verbose_name='Email')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'ordering': ('created_by', 'name'),
                'verbose_name_plural': 'Clientes',
                'verbose_name': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='ItemOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='ItemSell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('amount', models.FloatField(verbose_name='Precio de venta')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('amount', models.FloatField(verbose_name='Ingresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Pagos del cliente',
                'verbose_name': 'Pago del cliente',
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('last_modification_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('status', models.SmallIntegerField(choices=[(0, 'Cargada'), (1, 'Entregada'), (2, 'Rechazada')], verbose_name='Estado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sells.Customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'verbose_name': 'Venta',
            },
        ),
        migrations.AddField(
            model_name='itemsell',
            name='sell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sells.Sell', verbose_name='Venta'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sells.Order', verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='itemorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.Product', verbose_name='Producto'),
        ),
    ]
